name: Tofu Env Tests

on:
  pull_request:

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write

jobs:
  validate-plan-apply:
    name: Environment Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - dev
          - prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action with env (${{ matrix.env }})
        uses: ./
        with:
          workdir: test/valid
          env: ${{ matrix.env }}
          steps: validate,plan,apply
          summary-mode: full
          skip-plan-upload: true
          comment-mode: sticky
