name: Tofu Test Suites

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write

jobs:
  tofu-test-unit:
    name: OpenTofu Test (Unit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        uses: ./
        with:
          workdir: test/valid
          steps: test
          test-dir: tests/unit
          skip-plan-upload: true

  tofu-test-integration:
    name: OpenTofu Test (Integration)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run integration tests
        uses: ./
        with:
          workdir: test/valid
          steps: test
          test-dir: tests/integration
          skip-plan-upload: true
